from __future__ import annotations

from studymate.services.model_registry import MODELS


SETTINGS_SEARCH_INDEX_VERSION = "settings-search-v10"


def _entry(
    entry_id: str,
    *,
    kind: str,
    tab_key: str,
    tab_title: str,
    group_title: str,
    feature_label: str,
    target_key: str,
    description: str,
    aliases: list[str] | None = None,
) -> dict:
    return {
        "id": entry_id,
        "kind": kind,
        "tab_key": tab_key,
        "tab_title": tab_title,
        "group_title": group_title,
        "feature_label": feature_label,
        "target_key": target_key,
        "description": description,
        "aliases": list(aliases or []),
    }


SETTINGS_SEARCH_SEED = [
    _entry(
        "tab.general",
        kind="tab",
        tab_key="general",
        tab_title="General",
        group_title="General",
        feature_label="General tab",
        target_key="tab.general",
        description="Opens the student profile, account actions, Files To Cards defaults, MCQ defaults, and stats default settings.",
        aliases=["general settings", "profile settings page", "open general tab"],
    ),
    _entry(
        "general.appearance.group",
        kind="group",
        tab_key="general",
        tab_title="General",
        group_title="Appearance",
        feature_label="Appearance group",
        target_key="general.appearance.group",
        description="Contains the visual theme settings for choosing whether ONCard uses system, light, or dark mode.",
        aliases=["appearance card", "theme section", "dark mode section", "light mode section"],
    ),
    _entry(
        "general.appearance.theme",
        kind="widget",
        tab_key="general",
        tab_title="General",
        group_title="Appearance",
        feature_label="Theme",
        target_key="general.appearance.theme",
        description="Chooses the account theme preference: follow the system setting, force light mode, or force dark mode.",
        aliases=["dark mode", "light mode", "system theme", "theme picker", "appearance mode", "change theme"],
    ),
    _entry(
        "tab.ai",
        kind="tab",
        tab_key="ai",
        tab_title="AI",
        group_title="AI",
        feature_label="AI tab",
        target_key="tab.ai",
        description="Opens the AI configuration page for text models, OCR, cloud inference, semantic search, Ask AI style, and model management.",
        aliases=["ai settings", "model settings page", "open ai tab"],
    ),
    _entry(
        "tab.smart",
        kind="tab",
        tab_key="smart",
        tab_title="Smart features",
        group_title="Smart features",
        feature_label="Smart features tab",
        target_key="tab.smart",
        description="Opens the smart features page for per-feature context lengths and per-feature model routing.",
        aliases=["smart settings", "smart features settings", "context settings page", "context length settings", "token settings"],
    ),
    _entry(
        "tab.audio",
        kind="tab",
        tab_key="audio",
        tab_title="Audio",
        group_title="Audio",
        feature_label="Audio tab",
        target_key="tab.audio",
        description="Opens the audio configuration page for master sound, click sounds, transitions, and notification audio.",
        aliases=["sound settings", "audio settings page", "open audio tab"],
    ),
    _entry(
        "tab.performance",
        kind="tab",
        tab_key="performance",
        tab_title="Performance",
        group_title="Performance",
        feature_label="Performance tab",
        target_key="tab.performance",
        description="Opens the performance page for worker counts, startup warmup, motion preferences, and resource behavior.",
        aliases=["speed settings", "performance settings page", "open performance tab"],
    ),
    _entry(
        "general.profile.group",
        kind="group",
        tab_key="general",
        tab_title="General",
        group_title="Profile",
        feature_label="Profile group",
        target_key="general.profile.group",
        description="Contains the core student profile fields that ONCard uses when generating, grading, and personalizing study behavior.",
        aliases=["profile card", "student profile section", "basic profile settings"],
    ),
    _entry(
        "general.profile.user_name",
        kind="widget",
        tab_key="general",
        tab_title="General",
        group_title="Profile",
        feature_label="User name",
        target_key="general.profile.user_name",
        description="Stores the main student name ONCard uses in generated responses, grading tone, and personalized study text.",
        aliases=["student name", "change my name", "name field"],
    ),
    _entry(
        "general.profile.profile_name",
        kind="widget",
        tab_key="general",
        tab_title="General",
        group_title="Profile",
        feature_label="Profile name",
        target_key="general.profile.profile_name",
        description="Stores the profile label shown for the current student account, which can be different from the user name if needed.",
        aliases=["account profile name", "rename profile", "profile label"],
    ),
    _entry(
        "general.profile.age",
        kind="widget",
        tab_key="general",
        tab_title="General",
        group_title="Profile",
        feature_label="Age",
        target_key="general.profile.age",
        description="Sets the student age so ONCard can better match explanation style, pacing, and difficulty expectations.",
        aliases=["student age", "age setting", "change age"],
    ),
    _entry(
        "general.profile.hobbies",
        kind="widget",
        tab_key="general",
        tab_title="General",
        group_title="Profile",
        feature_label="Hobby/Interests",
        target_key="general.profile.hobbies",
        description="Stores the student interests so ONCard can reference familiar topics and examples in explanations and study material.",
        aliases=["interests", "hobbies", "favorite topics"],
    ),
    _entry(
        "general.profile.grade",
        kind="widget",
        tab_key="general",
        tab_title="General",
        group_title="Profile",
        feature_label="Grade",
        target_key="general.profile.grade",
        description="Sets the school grade or level so ONCard can calibrate wording and expected academic difficulty.",
        aliases=["school grade", "class year", "grade level"],
    ),
    _entry(
        "general.profile.gender",
        kind="widget",
        tab_key="general",
        tab_title="General",
        group_title="Profile",
        feature_label="Gender",
        target_key="general.profile.gender",
        description="Stores the student gender or custom pronouns so ONCard can address the student more naturally in generated text.",
        aliases=["pronouns", "gender field", "custom gender"],
    ),
    _entry(
        "general.profile.attention_span",
        kind="widget",
        tab_key="general",
        tab_title="General",
        group_title="Profile",
        feature_label="Attention span",
        target_key="general.profile.attention_span",
        description="Controls the expected minutes of focus per question, which helps ONCard tune pacing and response structure.",
        aliases=["focus time", "attention slider", "minutes per question"],
    ),
    _entry(
        "general.account.group",
        kind="group",
        tab_key="general",
        tab_title="General",
        group_title="Profile account actions",
        feature_label="Profile account actions group",
        target_key="general.account.group",
        description="Contains account management actions for exporting data, deleting the account, switching accounts, and creating a new account.",
        aliases=["account actions", "manage account section", "profile account controls"],
    ),
    _entry(
        "general.account.export",
        kind="action",
        tab_key="general",
        tab_title="General",
        group_title="Profile account actions",
        feature_label="Export account",
        target_key="general.account.export",
        description="Creates a downloadable copy of the current account data so it can be backed up or moved elsewhere.",
        aliases=["backup account", "download account", "export my data"],
    ),
    _entry(
        "general.account.delete",
        kind="action",
        tab_key="general",
        tab_title="General",
        group_title="Profile account actions",
        feature_label="Delete account",
        target_key="general.account.delete",
        description="Permanently removes the current account and its stored study data after confirmation.",
        aliases=["remove account", "erase account", "delete my profile"],
    ),
    _entry(
        "general.account.change",
        kind="action",
        tab_key="general",
        tab_title="General",
        group_title="Profile account actions",
        feature_label="Change account",
        target_key="general.account.change",
        description="Opens the account switch flow so another saved student profile can become active.",
        aliases=["switch account", "change user", "swap profile"],
    ),
    _entry(
        "general.account.new",
        kind="action",
        tab_key="general",
        tab_title="General",
        group_title="Profile account actions",
        feature_label="New account",
        target_key="general.account.new",
        description="Starts the flow for creating a fresh student account without overwriting the current one.",
        aliases=["create account", "new student profile", "add account"],
    ),
    _entry(
        "general.ftc.group",
        kind="group",
        tab_key="general",
        tab_title="General",
        group_title="FTC",
        feature_label="FTC group",
        target_key="general.ftc.group",
        description="Contains the default Files To Cards settings that shape how imported material is turned into study questions.",
        aliases=["files to cards section", "ftc settings", "import defaults"],
    ),
    _entry(
        "general.ftc.default_mode",
        kind="widget",
        tab_key="general",
        tab_title="General",
        group_title="FTC",
        feature_label="Default mode",
        target_key="general.ftc.default_mode",
        description="Sets the default Files To Cards mode so ONCard starts in either Standard or Force each time.",
        aliases=["ftc mode", "files to cards mode", "standard or force"],
    ),
    _entry(
        "general.ftc.question_standard",
        kind="widget",
        tab_key="general",
        tab_title="General",
        group_title="FTC",
        feature_label="Question quantity (Standard)",
        target_key="general.ftc.question_standard",
        description="Controls how many questions Files To Cards tries to generate when the Standard mode is selected.",
        aliases=["standard question count", "how many questions in standard", "ftc standard quantity"],
    ),
    _entry(
        "general.ftc.question_force",
        kind="widget",
        tab_key="general",
        tab_title="General",
        group_title="FTC",
        feature_label="Question quantity (Force)",
        target_key="general.ftc.question_force",
        description="Controls how many questions Files To Cards tries to force-generate when the Force mode is selected.",
        aliases=["force question count", "how many questions in force", "ftc force quantity"],
    ),
    _entry(
        "general.ftc.difficulty",
        kind="widget",
        tab_key="general",
        tab_title="General",
        group_title="FTC",
        feature_label="Difficulty",
        target_key="general.ftc.difficulty",
        description="Sets the default difficulty style for Files To Cards so generated questions start easier, normal, or harder by default.",
        aliases=["ftc difficulty", "files to cards difficulty", "question difficulty"],
    ),
    _entry(
        "general.ftc.ocr",
        kind="widget",
        tab_key="general",
        tab_title="General",
        group_title="FTC",
        feature_label="Files To Cards OCR",
        target_key="general.ftc.ocr",
        description="Turns OCR usage on or off for Files To Cards when importing PDFs, slides, and image-heavy source material.",
        aliases=["ftc ocr", "use ocr for files to cards", "ocr import setting"],
    ),
    _entry(
        "general.mcq.group",
        kind="group",
        tab_key="general",
        tab_title="General",
        group_title="MCQ",
        feature_label="MCQ group",
        target_key="general.mcq.group",
        description="Contains the controls for turning saved cards into multiple choice practice content.",
        aliases=["mcq section", "multiple choice settings", "cards to mcq group"],
    ),
    _entry(
        "general.mcq.enable",
        kind="widget",
        tab_key="general",
        tab_title="General",
        group_title="MCQ",
        feature_label="Enable Cards to MCQ",
        target_key="general.mcq.enable",
        description="Turns the Cards to MCQ workflow on or off so saved cards can be converted into multiple choice questions.",
        aliases=["enable mcq", "cards to mcq toggle", "multiple choice switch"],
    ),
    _entry(
        "general.mcq.difficulty",
        kind="widget",
        tab_key="general",
        tab_title="General",
        group_title="MCQ",
        feature_label="MCQ difficulty",
        target_key="general.mcq.difficulty",
        description="Sets the default difficulty level for generated multiple choice distractors and answer choices.",
        aliases=["mcq difficulty", "multiple choice difficulty", "harder mcq"],
    ),
    _entry(
        "general.mcq.run",
        kind="action",
        tab_key="general",
        tab_title="General",
        group_title="MCQ",
        feature_label="Cards to MCQ",
        target_key="general.mcq.run",
        description="Runs the Cards to MCQ generation action for the saved cards that are currently available.",
        aliases=["generate mcqs", "run cards to mcq", "convert cards to multiple choice"],
    ),
    _entry(
        "general.stats.group",
        kind="group",
        tab_key="general",
        tab_title="General",
        group_title="Stats defaults",
        feature_label="Stats defaults group",
        target_key="general.stats.group",
        description="Contains default behavior for the stats dialog so the preferred reporting range opens first.",
        aliases=["stats defaults", "default stats range section", "view stats defaults"],
    ),
    _entry(
        "general.stats.range",
        kind="widget",
        tab_key="general",
        tab_title="General",
        group_title="Stats defaults",
        feature_label="Default time range",
        target_key="general.stats.range",
        description="Sets the initial time range ONCard opens with in the View stats dialog, such as daily, weekly, or monthly.",
        aliases=["stats time range", "default stats range", "view stats period"],
    ),
    _entry(
        "ai.model.group",
        kind="group",
        tab_key="ai",
        tab_title="AI",
        group_title="AI-Model",
        feature_label="AI model group",
        target_key="ai.model.group",
        description="Contains the main text-model selectors that decide which model ONCard uses for text tasks and OCR.",
        aliases=["ai model section", "model picker group", "text model settings"],
    ),
    _entry(
        "ai.model.text",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="AI-Model",
        feature_label="Text AI model",
        target_key="ai.model.text",
        description="Chooses the main text model ONCard uses for cards, follow-up help, Ask AI, and other text generation features.",
        aliases=["text model", "main ai model", "default llm"],
    ),
    _entry(
        "ai.model.ocr",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="AI-Model",
        feature_label="OCR model",
        target_key="ai.model.ocr",
        description="Chooses the model ONCard uses when OCR or vision-style extraction is required for images, PDFs, and slides.",
        aliases=["ocr setting", "vision model", "image text model"],
    ),
    _entry(
        "ai.cloud.group",
        kind="group",
        tab_key="ai",
        tab_title="AI",
        group_title="Ollama cloud",
        feature_label="Ollama cloud group",
        target_key="ai.cloud.group",
        description="Contains the cloud inference controls for turning remote Ollama usage on, supplying an API key, and choosing a cloud variant.",
        aliases=["cloud inference section", "ollama cloud settings", "remote model settings"],
    ),
    _entry(
        "ai.cloud.enabled",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Ollama cloud",
        feature_label="Cloud inference",
        target_key="ai.cloud.enabled",
        description="Turns Ollama Cloud inference on or off so ONCard can use a remote model instead of the local text model selection.",
        aliases=["enable cloud", "cloud inference toggle", "use remote ollama"],
    ),
    _entry(
        "ai.cloud.api_key",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Ollama cloud",
        feature_label="API key",
        target_key="ai.cloud.api_key",
        description="Stores the Ollama Cloud API key required for authenticating cloud inference requests.",
        aliases=["cloud api key", "ollama key", "paste api key"],
    ),
    _entry(
        "ai.cloud.variant",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Ollama cloud",
        feature_label="Cloud model variant",
        target_key="ai.cloud.variant",
        description="Chooses which cloud model variant ONCard should use when cloud inference is enabled.",
        aliases=["cloud model", "cloud variant", "choose cloud model"],
    ),
    _entry(
        "ai.cloud.open_keys",
        kind="action",
        tab_key="ai",
        tab_title="AI",
        group_title="Ollama cloud",
        feature_label="Open API key page",
        target_key="ai.cloud.open_keys",
        description="Opens the Ollama Cloud key management page so a new API key can be created or copied.",
        aliases=["open ollama key page", "get api key", "cloud keys page"],
    ),
    _entry(
        "ai.cloud.refresh_models",
        kind="action",
        tab_key="ai",
        tab_title="AI",
        group_title="Ollama cloud",
        feature_label="Refresh cloud models",
        target_key="ai.cloud.refresh_models",
        description="Reloads the available cloud model variants that match ONCard's supported text models.",
        aliases=["refresh cloud model list", "reload cloud models", "update cloud variants"],
    ),
    _entry(
        "ai.runtime.group",
        kind="group",
        tab_key="ai",
        tab_title="AI",
        group_title="Ollama runtime",
        feature_label="Ollama runtime group",
        target_key="ai.runtime.group",
        description="Shows Ollama runtime status and provides the action for refreshing what models are currently available.",
        aliases=["runtime section", "ollama status", "local ollama runtime"],
    ),
    _entry(
        "ai.runtime.refresh_status",
        kind="action",
        tab_key="ai",
        tab_title="AI",
        group_title="Ollama runtime",
        feature_label="Refresh model status",
        target_key="ai.runtime.refresh_status",
        description="Checks the current Ollama installation and refreshes the local model availability state shown in settings.",
        aliases=["refresh local models", "reload model status", "check ollama status"],
    ),
    _entry(
        "ai.models.group",
        kind="group",
        tab_key="ai",
        tab_title="AI",
        group_title="Installed Ollama models",
        feature_label="Installed Ollama models group",
        target_key="ai.models.group",
        description="Lists the models ONCard knows how to use and exposes install, reinstall, or delete actions for each supported model.",
        aliases=["installed models section", "model install list", "ollama model list"],
    ),
    _entry(
        "ai.models.actions",
        kind="action",
        tab_key="ai",
        tab_title="AI",
        group_title="Installed Ollama models",
        feature_label="Install, reinstall, or delete model actions",
        target_key="ai.models.group",
        description="Covers the per-model actions used to install a missing model, reinstall an existing one, or remove it from the local runtime.",
        aliases=["install model", "reinstall model", "delete model"],
    ),
    _entry(
        "ai.context.group",
        kind="group",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Context group",
        target_key="ai.context.group",
        description="Contains the per-feature context controls and per-feature model selectors that decide how much text each AI task can read and which model it should use.",
        aliases=["context section", "sequence lengths", "token limits group"],
    ),
    _entry(
        "ai.context.autofill",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Card autofill",
        target_key="ai.context.autofill",
        description="Controls how much context the card autofill feature can read when generating metadata, hints, and a starter answer.",
        aliases=["autofill context length", "card autofill tokens", "autofill limit"],
    ),
    _entry(
        "ai.context.autofill.model",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Card autofill model",
        target_key="ai.context.autofill.model",
        description="Chooses the specific model card autofill should use. Text Model means it follows the main AI text model setting.",
        aliases=["autofill model", "card autofill model", "autofill text model"],
    ),
    _entry(
        "ai.context.grading",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Answer grading",
        target_key="ai.context.grading",
        description="Controls how much context the written-answer grading flow can use when producing marks and feedback.",
        aliases=["grading context length", "answer grading tokens", "grading limit"],
    ),
    _entry(
        "ai.context.grading.model",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Answer grading model",
        target_key="ai.context.grading.model",
        description="Chooses the specific model answer grading should use. Text Model means it follows the main AI text model setting.",
        aliases=["grading model", "answer grading model", "feedback model"],
    ),
    _entry(
        "ai.context.mcq",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="MCQ generation",
        target_key="ai.context.mcq",
        description="Controls how much context the MCQ generator can use when building multiple-choice answers and distractors.",
        aliases=["mcq context length", "mcq tokens", "multiple choice limit"],
    ),
    _entry(
        "ai.context.mcq.model",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="MCQ generation model",
        target_key="ai.context.mcq.model",
        description="Chooses the specific model MCQ generation should use. Text Model means it follows the main AI text model setting.",
        aliases=["mcq model", "multiple choice model", "cards to mcq model"],
    ),
    _entry(
        "ai.context.ask_planner",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Ask AI planner",
        target_key="ai.context.ask_planner",
        description="Controls how much context the Ask AI planner can examine before deciding whether to search cards, browse images, or answer directly.",
        aliases=["ask ai planner tokens", "planner context length", "ask ai decision model"],
    ),
    _entry(
        "ai.context.ask_planner.model",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Ask AI planner model",
        target_key="ai.context.ask_planner.model",
        description="Chooses the specific model the Ask AI planner should use. Text Model means it follows the main AI text model setting.",
        aliases=["ask ai planner model", "planner model", "ask ai routing model"],
    ),
    _entry(
        "ai.context.ask_answer",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Ask AI answer",
        target_key="ai.context.ask_answer",
        description="Controls how much context the Ask AI answer step can read while writing the final response.",
        aliases=["ask ai answer tokens", "final answer context", "ask ai response limit"],
    ),
    _entry(
        "ai.context.ask_answer.model",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Ask AI answer model",
        target_key="ai.context.ask_answer.model",
        description="Chooses the specific model the Ask AI answer step should use. Text Model means it follows the main AI text model setting.",
        aliases=["ask ai answer model", "ask ai response model", "final answer model"],
    ),
    _entry(
        "ai.context.ask_image",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Image search terms",
        target_key="ai.context.ask_image",
        description="Controls how much context the image search term extractor can use when converting an image into searchable study terms.",
        aliases=["image search tokens", "image context length", "search image terms"],
    ),
    _entry(
        "ai.context.ask_image.model",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Image search terms model",
        target_key="ai.context.ask_image.model",
        description="Chooses the specific model image search term generation should use. Text Model means it follows the main AI text model setting.",
        aliases=["image search model", "image terms model", "ask ai image model"],
    ),
    _entry(
        "ai.context.wiki",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Wiki Summarizer",
        target_key="ai.context.wiki",
        description="Controls how much context the Wikipedia breakdown flow can use when simplifying retrieved source material.",
        aliases=["wiki context length", "wikipedia tokens", "wiki breakdown limit"],
    ),
    _entry(
        "ai.context.wiki.model",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Wiki Summarizer model",
        target_key="ai.context.wiki.model",
        description="Chooses the specific model Wiki Summarizer should use. Text Model means it follows the main AI text model setting.",
        aliases=["wiki model", "wiki summarizer model", "wikipedia breakdown model"],
    ),
    _entry(
        "ai.context.followup",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Follow-up chat",
        target_key="ai.context.followup",
        description="Controls how much context the follow-up chat can use when answering questions about the current card and feedback.",
        aliases=["follow up context", "chat followup tokens", "follow-up limit"],
    ),
    _entry(
        "ai.context.followup.model",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Follow-up chat model",
        target_key="ai.context.followup.model",
        description="Chooses the specific model follow-up chat should use. Text Model means it follows the main AI text model setting.",
        aliases=["follow-up model", "followup model", "discuss more model"],
    ),
    _entry(
        "ai.context.reinforcement",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Reinforcement cards",
        target_key="ai.context.reinforcement",
        description="Controls how much context the reinforcement-card generator can use after weak answers.",
        aliases=["reinforcement context", "temporary practice card tokens", "reinforcement limit"],
    ),
    _entry(
        "ai.context.reinforcement.model",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Reinforcement cards model",
        target_key="ai.context.reinforcement.model",
        description="Chooses the specific model reinforcement card generation should use. Text Model means it follows the main AI text model setting.",
        aliases=["reinforcement model", "practice cards model", "weak answer card model"],
    ),
    _entry(
        "ai.context.ftc_ocr",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Files To Cards OCR",
        target_key="ai.context.ftc_ocr",
        description="Controls how much context OCR extraction can use before Files To Cards starts generating study material.",
        aliases=["ftc ocr context", "files to cards ocr tokens", "ocr token limit"],
    ),
    _entry(
        "ai.context.ftc_ocr.model",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Files To Cards OCR model",
        target_key="ai.context.ftc_ocr.model",
        description="Chooses the specific model the Files To Cards OCR stage should use. Text Model means it follows the main AI text model setting.",
        aliases=["ftc ocr model", "files to cards ocr model", "ocr extraction model"],
    ),
    _entry(
        "ai.context.ftc_paper",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Files To Cards paper",
        target_key="ai.context.ftc_paper",
        description="Controls how much context the revision-note stage of Files To Cards can use when reading source material.",
        aliases=["ftc paper context", "revision notes tokens", "paper token limit"],
    ),
    _entry(
        "ai.context.ftc_paper.model",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Files To Cards paper model",
        target_key="ai.context.ftc_paper.model",
        description="Chooses the specific model the Files To Cards paper stage should use. Text Model means it follows the main AI text model setting.",
        aliases=["ftc paper model", "files to cards paper model", "revision notes model"],
    ),
    _entry(
        "ai.context.ftc_cards",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Files To Cards cards",
        target_key="ai.context.ftc_cards",
        description="Controls how much context the final card-generation stage of Files To Cards can use when creating study cards from notes.",
        aliases=["ftc cards context", "files to cards card tokens", "final cards token limit"],
    ),
    _entry(
        "ai.context.ftc_cards.model",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Files To Cards cards model",
        target_key="ai.context.ftc_cards.model",
        description="Chooses the specific model the Files To Cards card stage should use. Text Model means it follows the main AI text model setting.",
        aliases=["ftc cards model", "files to cards cards model", "card generation model"],
    ),
    _entry(
        "ai.context.stats",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Stats summary",
        target_key="ai.context.stats",
        description="Controls how much context the AI stats summary can use when describing performance and study trends.",
        aliases=["stats summary tokens", "stats ai context", "stats token limit"],
    ),
    _entry(
        "ai.context.stats.model",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Context",
        feature_label="Stats summary model",
        target_key="ai.context.stats.model",
        description="Chooses the specific model the stats summary should use. Text Model means it follows the main AI text model setting.",
        aliases=["stats model", "stats summary model", "performance summary model"],
    ),
    _entry(
        "ai.ask_style.group",
        kind="group",
        tab_key="ai",
        tab_title="AI",
        group_title="Ask AI style",
        feature_label="Ask AI style group",
        target_key="ai.ask_style.group",
        description="Contains the saved Ask AI tone and emoji controls that shape the personality of Ask AI responses.",
        aliases=["ask ai style", "ask ai tone section", "assistant personality settings"],
    ),
    _entry(
        "ai.ask_style.ask_tone",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Ask AI style",
        feature_label="Ask AI tone",
        target_key="ai.ask_style.ask_tone",
        description="Sets the default tone style Ask AI should lean toward, such as warm, funny, sarcastic, or other presets.",
        aliases=["ask ai tone", "assistant tone", "change ai style"],
    ),
    _entry(
        "ai.ask_style.ask_emoji",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Ask AI style",
        feature_label="Ask AI emoji level",
        target_key="ai.ask_style.ask_emoji",
        description="Controls how many emojis Ask AI is allowed to use by default when writing its responses.",
        aliases=["emoji level", "ask ai emoji setting", "emoji amount"],
    ),
    _entry(
        "ai.search.group",
        kind="group",
        tab_key="ai",
        tab_title="AI",
        group_title="Search",
        feature_label="Search group",
        target_key="ai.search.group",
        description="Contains the settings that control semantic search behavior and how many terms image search should generate.",
        aliases=["search section", "semantic search settings", "ai search group"],
    ),
    _entry(
        "ai.search.mode",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Search",
        feature_label="Search mode",
        target_key="ai.search.mode",
        description="Turns Neural Acceleration semantic search on or off so ONCard can use embeddings instead of keyword-only matching.",
        aliases=["neural acceleration", "semantic search toggle", "search mode"],
    ),
    _entry(
        "ai.search.image_terms",
        kind="widget",
        tab_key="ai",
        tab_title="AI",
        group_title="Search",
        feature_label="Image Search",
        target_key="ai.search.image_terms",
        description="Controls how many search terms ONCard should generate from an image before searching the card set.",
        aliases=["image search term count", "how many image terms", "image search setting"],
    ),
    _entry(
        "audio.group",
        kind="group",
        tab_key="audio",
        tab_title="Audio",
        group_title="Audio",
        feature_label="Audio group",
        target_key="audio.group",
        description="Contains all sound-related preferences including the master audio toggle and sound choices for clicks, transitions, and notifications.",
        aliases=["audio section", "sound group", "sound preferences"],
    ),
    _entry(
        "audio.master",
        kind="widget",
        tab_key="audio",
        tab_title="Audio",
        group_title="Audio",
        feature_label="Master audio",
        target_key="audio.master",
        description="Turns all ONCard interface sounds on or off from one main switch.",
        aliases=["master sound", "disable all sounds", "audio toggle"],
    ),
    _entry(
        "audio.click_enabled",
        kind="widget",
        tab_key="audio",
        tab_title="Audio",
        group_title="Audio",
        feature_label="Mouse Click",
        target_key="audio.click_enabled",
        description="Turns the mouse-click sound effect on or off for button presses and slider interactions.",
        aliases=["click sound toggle", "mouse click audio", "button click sound"],
    ),
    _entry(
        "audio.click_sound",
        kind="widget",
        tab_key="audio",
        tab_title="Audio",
        group_title="Audio",
        feature_label="Mouse Click sound",
        target_key="audio.click_sound",
        description="Chooses which click sound ONCard should play when click sounds are enabled.",
        aliases=["click sound choice", "pick click sound", "mouse click sound type"],
    ),
    _entry(
        "audio.transition_enabled",
        kind="widget",
        tab_key="audio",
        tab_title="Audio",
        group_title="Audio",
        feature_label="Transition",
        target_key="audio.transition_enabled",
        description="Turns the transition swoosh sound on or off when ONCard moves between interface states.",
        aliases=["transition sound toggle", "page swoosh sound", "screen transition audio"],
    ),
    _entry(
        "audio.transition_sound",
        kind="widget",
        tab_key="audio",
        tab_title="Audio",
        group_title="Audio",
        feature_label="Transition sound",
        target_key="audio.transition_sound",
        description="Chooses which transition sound ONCard should use when transition audio is enabled.",
        aliases=["transition sound choice", "pick swoosh sound", "transition audio type"],
    ),
    _entry(
        "audio.notification_sound",
        kind="widget",
        tab_key="audio",
        tab_title="Audio",
        group_title="Audio",
        feature_label="Notification",
        target_key="audio.notification_sound",
        description="Chooses which notification sound ONCard should play for desktop-style notifications and task completion alerts.",
        aliases=["notification sound", "alert sound", "toast sound"],
    ),
    _entry(
        "account.avatar.group",
        kind="group",
        tab_key="account",
        tab_title="Account",
        group_title="Avatar",
        feature_label="Avatar group",
        target_key="account.avatar.group",
        description="Contains the avatar and profile picture controls, including the current avatar preview, avatar picker grid, and random avatar action.",
        aliases=[
            "avatar",
            "avatar settings",
            "change avatar",
            "change my avatar",
            "profile picture",
            "change profile picture",
            "profile pic",
            "change profile pic",
            "pfp",
            "change pfp",
            "avatar changer",
            "edit avatar",
            "random avatar",
            "profile photo",
            "change profile photo",
        ],
    ),
    _entry(
        "performance.group",
        kind="group",
        tab_key="performance",
        tab_title="Performance",
        group_title="Performance",
        feature_label="Performance group",
        target_key="performance.group",
        description="Contains the controls that affect startup warmup, worker counts, and motion behavior across the app.",
        aliases=["performance section", "speed group", "resource settings"],
    ),
    _entry(
        "performance.mode",
        kind="widget",
        tab_key="performance",
        tab_title="Performance",
        group_title="Performance",
        feature_label="Mode",
        target_key="performance.mode",
        description="Switches performance handling between Auto defaults and Manual control of worker counts.",
        aliases=["performance mode", "auto or manual", "manual performance"],
    ),
    _entry(
        "performance.startup_workers",
        kind="widget",
        tab_key="performance",
        tab_title="Performance",
        group_title="Performance",
        feature_label="Startup workers",
        target_key="performance.startup_workers",
        description="Controls how many workers ONCard uses during startup-related work when manual performance mode is enabled.",
        aliases=["startup worker count", "workers on startup", "boot worker threads"],
    ),
    _entry(
        "performance.background_workers",
        kind="widget",
        tab_key="performance",
        tab_title="Performance",
        group_title="Performance",
        feature_label="Background workers",
        target_key="performance.background_workers",
        description="Controls how many workers ONCard uses for background tasks when manual performance mode is enabled.",
        aliases=["background worker count", "worker threads", "background jobs"],
    ),
    _entry(
        "performance.startup_warmup",
        kind="widget",
        tab_key="performance",
        tab_title="Performance",
        group_title="Performance",
        feature_label="Startup warmup",
        target_key="performance.startup_warmup",
        description="Turns startup cache warming on or off so ONCard can pre-load common data when the app launches.",
        aliases=["warm cache on startup", "startup warmup toggle", "preload cache"],
    ),
    _entry(
        "performance.reduced_motion",
        kind="widget",
        tab_key="performance",
        tab_title="Performance",
        group_title="Performance",
        feature_label="Reduced motion",
        target_key="performance.reduced_motion",
        description="Turns reduced-motion mode on or off so animations and movement-heavy effects can be minimized.",
        aliases=["reduce animations", "motion setting", "disable movement effects"],
    ),
]

for _seed_entry in SETTINGS_SEARCH_SEED:
    _entry_id = str(_seed_entry.get("id", ""))
    if _entry_id.startswith("ai.context"):
        _smart_id = "smart.context" + _entry_id[len("ai.context") :]
        _seed_entry["id"] = _smart_id
        _seed_entry["tab_key"] = "smart"
        _seed_entry["tab_title"] = "Smart features"
        _seed_entry["target_key"] = _smart_id
    _target_key = str(_seed_entry.get("target_key", ""))
    _feature_label = str(_seed_entry.get("feature_label", "")).strip()
    _aliases = [str(alias).strip() for alias in list(_seed_entry.get("aliases", [])) if str(alias).strip()]
    if _target_key.startswith("smart.context.") and _target_key.endswith(".model") and _feature_label:
        _task_name = _feature_label.removesuffix(" model").strip()
        _aliases.extend(
            [
                f"change model for {_task_name.lower()}",
                f"model for {_task_name.lower()}",
                f"which model does {_task_name.lower()} use",
                f"{_task_name.lower()} ai model",
                f"{_task_name.lower()} task model",
            ]
        )
        _seed_entry["aliases"] = list(dict.fromkeys(_aliases))

for _spec in MODELS.values():
    SETTINGS_SEARCH_SEED.append(
        _entry(
            f"ai.models.{_spec.key}",
            kind="action",
            tab_key="ai",
            tab_title="AI",
            group_title="Installed Ollama models",
            feature_label=f"{_spec.display_name} model actions",
            target_key=f"ai.models.{_spec.key}",
            description=f"Jumps to the {_spec.display_name} model row so you can install, reinstall, or delete that specific Ollama model.",
            aliases=[
                _spec.display_name,
                _spec.primary_tag,
                f"install {_spec.display_name}",
                f"reinstall {_spec.display_name}",
                f"delete {_spec.display_name}",
                f"remove {_spec.display_name}",
                f"change to {_spec.display_name}",
                f"use {_spec.display_name}",
            ],
        )
    )
